/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../sanity.schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h2' | 'h3' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'external' | 'internal'
        href?: string
        route?: string
        newTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | ({
      _key: string
    } & Code)
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      caption?: string
      _type: 'image'
      _key: string
    }
>

export type Seo = {
  _type: 'seo'
  metaTitle?: string
  metaDescription?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
}

export type QaAction = {
  _type: 'qaAction'
  cmd?: string
  flag?: string
  route?: Array<string>
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type CtaCommand = {
  _type: 'ctaCommand'
  cmd: string
  flag?: string
  sub?: string
  primary?: boolean
  route?: Array<string>
  file?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
}

export type StackRow = {
  _type: 'stackRow'
  term?: string
  items?: Array<string>
}

export type ValueItem = {
  _type: 'valueItem'
  key?: string
  value?: string
}

export type TimelineEntry = {
  _type: 'timelineEntry'
  years?: string
  role?: string
  company?: string
  body?: string
  current?: boolean
}

export type Metric = {
  _type: 'metric'
  value?: string
  unit?: string
  label?: string
}

export type QaEntry = {
  _id: string
  _type: 'qaEntry'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  keywords: Array<string>
  answer?: Array<string>
  action?: QaAction
  enabled?: boolean
}

export type Tag = {
  _id: string
  _type: 'tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type CategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'category'
}

export type TagReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'tag'
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  summary: string
  date: string
  category: CategoryReference
  tags?: Array<
    {
      _key: string
    } & TagReference
  >
  readTime?: number
  featured?: boolean
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    imagePrompt?: string
    _type: 'image'
  }
  body?: BlockContent
  seo?: Seo
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Category = {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  description?: string
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  commit: string
  status: 'live' | 'shipped' | 'active' | 'archived'
  tags: Array<
    {
      _key: string
    } & TagReference
  >
  role?: string
  problem: string
  solution: string
  stack?: Array<string>
  impact?: Array<string>
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    imagePrompt?: string
    _type: 'image'
  }
  gallery?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'image'
    _key: string
  }>
  repo?: string
  live?: string
  order?: number
  seo?: Seo
}

export type ContactPage = {
  _id: string
  _type: 'contactPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  eyebrow?: string
  heading?: string
  intro?: string
  formTitle?: string
  formBadge?: string
  nameField?: {
    label?: string
    placeholder?: string
  }
  emailField?: {
    label?: string
    placeholder?: string
  }
  messageField?: {
    label?: string
    placeholder?: string
  }
  submitLabel?: string
  formNote?: string
  validationMessages?: {
    nameRequired?: string
    emailRequired?: string
    emailInvalid?: string
    messageRequired?: string
    messageTooShort?: string
  }
  successPanelTitle?: string
  successLines?: Array<string>
  successGreeting?: string
  sendAnotherLabel?: string
  availabilityHeading?: string
  availabilityText?: string
  resumeLabel?: string
  seo?: Seo
}

export type BlogPage = {
  _id: string
  _type: 'blogPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  eyebrow?: string
  heading?: string
  intro?: string
  featuredPanelTitle?: string
  featuredBadge?: string
  readButtonLabel?: string
  searchPlaceholder?: string
  noMatchesText?: string
  loadingText?: string
  endText?: string
  archiveLabel?: string
  archiveNote?: string
  articleLabels?: {
    tocHeading?: string
    searchHeading?: string
    categoriesHeading?: string
    tagsHeading?: string
    recentHeading?: string
    archivesHeading?: string
    readingTimeHeading?: string
    categoryHeading?: string
    moreNotesHeading?: string
    backLabel?: string
    figCaptionPrefix?: string
  }
  seo?: Seo
}

export type PortfolioPage = {
  _id: string
  _type: 'portfolioPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  eyebrow?: string
  heading?: string
  intro?: string
  filterLabel?: string
  matchesText?: string
  loadingText?: string
  endText?: string
  detailLabels?: {
    deployLogTitle?: string
    deployLogLines?: Array<string>
    briefHeading?: string
    problemLabel?: string
    solutionLabel?: string
    stackLabel?: string
    roleLabel?: string
    impactHeading?: string
    interfaceHeading?: string
    cloneLabel?: string
    openLiveLabel?: string
    backLabel?: string
    prevLabel?: string
    nextLabel?: string
  }
  seo?: Seo
}

export type AboutPage = {
  _id: string
  _type: 'aboutPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  eyebrow?: string
  heading?: string
  portraitCaption?: string
  bioParagraphs?: Array<string>
  experiencePrompt?: string
  timeline?: Array<
    {
      _key: string
    } & TimelineEntry
  >
  valuesPrompt?: string
  values?: Array<
    {
      _key: string
    } & ValueItem
  >
  stackPrompt?: string
  stackRows?: Array<
    {
      _key: string
    } & StackRow
  >
  ctas?: Array<
    {
      _key: string
    } & CtaCommand
  >
  seo?: Seo
}

export type ProjectReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'project'
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  heroWord: string
  promptCommand?: string
  toolActions?: Array<string>
  successLines?: Array<string>
  portraitCaption?: string
  featuredHeading?: string
  featuredProjects?: Array<
    {
      _key: string
    } & ProjectReference
  >
  metricsHeading?: string
  metrics?: Array<
    {
      _key: string
    } & Metric
  >
  nextStepsHeading?: string
  nextSteps?: Array<
    {
      _key: string
    } & CtaCommand
  >
  systemCard?: {
    roleLine?: string
    kvRows?: Array<
      {
        _key: string
      } & ValueItem
    >
  }
  seo?: Seo
}

export type Navigation = {
  _id: string
  _type: 'navigation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  items?: Array<{
    label: string
    command: string
    route?: Array<string>
    _type: 'item'
    _key: string
  }>
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  handle: string
  headline: string
  shortBio: string
  email: string
  location?: string
  availability?: string
  availabilityStatus?: boolean
  cv?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
  portrait?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  github?: string
  linkedin?: string
  theme?: {
    accentColor?: Color
    grain?: boolean
    heroLayout?: 'boot' | 'split'
  }
  askConsole?: {
    enabled?: boolean
    heading?: string
    description?: string
    placeholder?: string
    emptyMessage?: string
    suggestions?: Array<string>
    fallback?: Array<string>
  }
  statusbar?: {
    branchLabel?: string
    statusText?: string
  }
  uiText?: {
    notFoundTitle?: string
    notFoundBody?: string
    commandPalettePlaceholder?: string
    mobileConsolePrompt?: string
    newSessionLabel?: string
    copyEmailLabel?: string
  }
  seo?: Seo
}

export type Color = {
  _type: 'color'
  hex?: string
  alpha?: number
  hsl?: HslaColor
  hsv?: HsvaColor
  rgb?: RgbaColor
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type Code = {
  _type: 'code'
  language?: string
  filename?: string
  code?: string
  highlightedLines?: Array<number>
}

export type RgbaColor = {
  _type: 'rgbaColor'
  r?: number
  g?: number
  b?: number
  a?: number
}

export type HsvaColor = {
  _type: 'hsvaColor'
  h?: number
  s?: number
  v?: number
  a?: number
}

export type HslaColor = {
  _type: 'hslaColor'
  h?: number
  s?: number
  l?: number
  a?: number
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | BlockContent
  | Seo
  | QaAction
  | SanityFileAssetReference
  | CtaCommand
  | StackRow
  | ValueItem
  | TimelineEntry
  | Metric
  | QaEntry
  | Tag
  | Slug
  | CategoryReference
  | TagReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Category
  | Project
  | ContactPage
  | BlogPage
  | PortfolioPage
  | AboutPage
  | ProjectReference
  | HomePage
  | Navigation
  | SiteSettings
  | Color
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | Code
  | RgbaColor
  | HsvaColor
  | HslaColor
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = null

// Source: sanity/lib/queries.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    name,    headline,    shortBio,    github,    linkedin,    seo {      metaTitle,      metaDescription,      ogImage    }  }
export type SETTINGS_QUERY_RESULT = {
  name: string
  headline: string
  shortBio: string
  github: string | null
  linkedin: string | null
  seo: {
    metaTitle: string | null
    metaDescription: string | null
    ogImage: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      metadataBase?: string
      _type: 'image'
    } | null
  } | null
} | null

// Source: sanity/lib/queries.ts
// Variable: HOME_PAGE_META_QUERY
// Query: *[_id == "homePage"][0]{    seo {      metaTitle,      metaDescription,      ogImage    }  }
export type HOME_PAGE_META_QUERY_RESULT =
  | {
      seo: null
    }
  | {
      seo: {
        metaTitle: string | null
        metaDescription: string | null
        ogImage: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          metadataBase?: string
          _type: 'image'
        } | null
      } | null
    }
  | null

// Source: sanity/lib/queries.ts
// Variable: ABOUT_PAGE_META_QUERY
// Query: *[_id == "aboutPage"][0]{    seo {      metaTitle,      metaDescription,      ogImage    }  }
export type ABOUT_PAGE_META_QUERY_RESULT =
  | {
      seo: null
    }
  | {
      seo: {
        metaTitle: string | null
        metaDescription: string | null
        ogImage: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          metadataBase?: string
          _type: 'image'
        } | null
      } | null
    }
  | null

// Source: sanity/lib/queries.ts
// Variable: PORTFOLIO_PAGE_META_QUERY
// Query: *[_id == "portfolioPage"][0]{    heading,    intro,    seo {      metaTitle,      metaDescription,      ogImage    }  }
export type PORTFOLIO_PAGE_META_QUERY_RESULT =
  | {
      heading: null
      intro: null
      seo: null
    }
  | {
      heading: null
      intro: null
      seo: {
        metaTitle: string | null
        metaDescription: string | null
        ogImage: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          metadataBase?: string
          _type: 'image'
        } | null
      } | null
    }
  | {
      heading: string | null
      intro: null
      seo: {
        metaTitle: string | null
        metaDescription: string | null
        ogImage: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          metadataBase?: string
          _type: 'image'
        } | null
      } | null
    }
  | {
      heading: string | null
      intro: string | null
      seo: {
        metaTitle: string | null
        metaDescription: string | null
        ogImage: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          metadataBase?: string
          _type: 'image'
        } | null
      } | null
    }
  | null

// Source: sanity/lib/queries.ts
// Variable: BLOG_PAGE_META_QUERY
// Query: *[_id == "blogPage"][0]{    heading,    intro,    seo {      metaTitle,      metaDescription,      ogImage    }  }
export type BLOG_PAGE_META_QUERY_RESULT =
  | {
      heading: null
      intro: null
      seo: null
    }
  | {
      heading: null
      intro: null
      seo: {
        metaTitle: string | null
        metaDescription: string | null
        ogImage: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          metadataBase?: string
          _type: 'image'
        } | null
      } | null
    }
  | {
      heading: string | null
      intro: null
      seo: {
        metaTitle: string | null
        metaDescription: string | null
        ogImage: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          metadataBase?: string
          _type: 'image'
        } | null
      } | null
    }
  | {
      heading: string | null
      intro: string | null
      seo: {
        metaTitle: string | null
        metaDescription: string | null
        ogImage: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          metadataBase?: string
          _type: 'image'
        } | null
      } | null
    }
  | null

// Source: sanity/lib/queries.ts
// Variable: CONTACT_PAGE_META_QUERY
// Query: *[_id == "contactPage"][0]{    heading,    seo {      metaTitle,      metaDescription,      ogImage    }  }
export type CONTACT_PAGE_META_QUERY_RESULT =
  | {
      heading: null
      seo: null
    }
  | {
      heading: null
      seo: {
        metaTitle: string | null
        metaDescription: string | null
        ogImage: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          metadataBase?: string
          _type: 'image'
        } | null
      } | null
    }
  | {
      heading: string | null
      seo: {
        metaTitle: string | null
        metaDescription: string | null
        ogImage: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          metadataBase?: string
          _type: 'image'
        } | null
      } | null
    }
  | null

// Source: sanity/lib/queries.ts
// Variable: PROJECT_META_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{    title,    "slug": slug.current,    _updatedAt,    coverImage,    seo {      metaTitle,      metaDescription,      ogImage    }  }
export type PROJECT_META_QUERY_RESULT = {
  title: string
  slug: string
  _updatedAt: string
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    imagePrompt?: string
    _type: 'image'
  }
  seo: {
    metaTitle: string | null
    metaDescription: string | null
    ogImage: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      metadataBase?: string
      _type: 'image'
    } | null
  } | null
} | null

// Source: sanity/lib/queries.ts
// Variable: POST_META_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    title,    summary,    "slug": slug.current,    date,    _updatedAt,    coverImage,    seo {      metaTitle,      metaDescription,      ogImage    }  }
export type POST_META_QUERY_RESULT = {
  title: string
  summary: string
  slug: string
  date: string
  _updatedAt: string
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    imagePrompt?: string
    _type: 'image'
  }
  seo: {
    metaTitle: string | null
    metaDescription: string | null
    ogImage: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      metadataBase?: string
      _type: 'image'
    } | null
  } | null
} | null

// Source: sanity/lib/queries.ts
// Variable: PROJECTS_SLUG_QUERY
// Query: *[_type == "project" && defined(slug.current)]{    "slug": slug.current,    _updatedAt  }
export type PROJECTS_SLUG_QUERY_RESULT = Array<{
  slug: string
  _updatedAt: string
}>

// Source: sanity/lib/queries.ts
// Variable: POSTS_SLUG_QUERY
// Query: *[_type == "post" && defined(slug.current)]{    "slug": slug.current,    date,    _updatedAt  }
export type POSTS_SLUG_QUERY_RESULT = Array<{
  slug: string
  date: string
  _updatedAt: string
}>

// Source: sanity/lib/queries.ts
// Variable: RSS_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(date desc) [0...20] {    title,    "slug": slug.current,    summary,    date,    "categoryTitle": category->title  }
export type RSS_POSTS_QUERY_RESULT = Array<{
  title: string
  slug: string
  summary: string
  date: string
  categoryTitle: string
}>

// Source: sanity/lib/queries.ts
// Variable: allPostsQuery
// Query: *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {    _id,    "status": select(_originalId in path("drafts.**") => "draft", "published"),    "title": coalesce(title, "Untitled"),    "slug": slug.current,    excerpt,    coverImage,    "date": coalesce(date, _updatedAt),    "author": author->{firstName, lastName, picture},  }
export type AllPostsQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    imagePrompt?: string
    _type: 'image'
  }
  date: string
  author: null
}>

// Source: sanity/lib/queries.ts
// Variable: morePostsQuery
// Query: *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {    _id,    "status": select(_originalId in path("drafts.**") => "draft", "published"),    "title": coalesce(title, "Untitled"),    "slug": slug.current,    excerpt,    coverImage,    "date": coalesce(date, _updatedAt),    "author": author->{firstName, lastName, picture},  }
export type MorePostsQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    imagePrompt?: string
    _type: 'image'
  }
  date: string
  author: null
}>

// Source: sanity/lib/queries.ts
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug] [0] {    content[]{      ...,      markDefs[]{        ...,        _type == "link" => {          "page": page->slug.current,          "post": post->slug.current        }      }    },    _id,    "status": select(_originalId in path("drafts.**") => "draft", "published"),    "title": coalesce(title, "Untitled"),    "slug": slug.current,    excerpt,    coverImage,    "date": coalesce(date, _updatedAt),    "author": author->{firstName, lastName, picture},  }
export type PostQueryResult = {
  content: null
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    imagePrompt?: string
    _type: 'image'
  }
  date: string
  author: null
} | null

// Source: sanity/lib/queries.ts
// Variable: postPagesSlugs
// Query: *[_type == "post" && defined(slug.current)]  {"slug": slug.current}
export type PostPagesSlugsResult = Array<{
  slug: string
}>

// Source: sanity/lib/queries.ts
// Variable: pagesSlugs
// Query: *[_type == "page" && defined(slug.current)]  {"slug": slug.current}
export type PagesSlugsResult = Array<never>

// Source: sanity/lib/queries.ts
// Variable: getPageQuery
// Query: *[_type == 'page' && slug.current == $slug][0]{    _id,    _type,    name,    slug,    heading,    subheading,    "pageBuilder": pageBuilder[]{      ...,      _type == "callToAction" => {        ...,        button {          ...,          link {            ...,            _type == "link" => {              "page": page->slug.current,              "post": post->slug.current            }          }        }      },      _type == "infoSection" => {        content[]{          ...,          markDefs[]{            ...,            _type == "link" => {              "page": page->slug.current,              "post": post->slug.current            }          }        }      },    },  }
export type GetPageQueryResult = null

// Source: sanity/lib/queries.ts
// Variable: sitemapData
// Query: *[_type == "page" || _type == "post" && defined(slug.current)] | order(_type asc) {    "slug": slug.current,    _type,    _updatedAt,  }
export type SitemapDataResult = Array<{
  slug: string
  _type: 'post'
  _updatedAt: string
}>

// Source: sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]{    _id,    siteTitle,    tagline,    bio,    email,    github,    linkedin,    twitter,    "portrait": portrait{asset, alt, crop, hotspot},    "seo": seo{title, description, ogImage},    "theme": theme{accentColor, grain, heroLayout},    "homePage": homePage{      heroHeading,      heroSub,      heroBio,      "metrics": metrics[]{_key, number, unit, label},      "nextSteps": nextSteps[]{_key, cmd, flag, description},      "featuredProjects": featuredProjects[]->{_id, title, "slug": slug.current, commit, status, tags},      "systemCard": systemCard{        "kvRows": kvRows[]{_key, key, value}      }    }  }
export type SiteSettingsQueryResult = {
  _id: string
  siteTitle: null
  tagline: null
  bio: null
  email: string
  github: string | null
  linkedin: string | null
  twitter: null
  portrait: {
    asset: SanityImageAssetReference | null
    alt: string | null
    crop: SanityImageCrop | null
    hotspot: SanityImageHotspot | null
  } | null
  seo: {
    title: null
    description: null
    ogImage: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      metadataBase?: string
      _type: 'image'
    } | null
  } | null
  theme: {
    accentColor: Color | null
    grain: boolean | null
    heroLayout: 'boot' | 'split' | null
  } | null
  homePage: null
} | null

// Source: sanity/lib/queries.ts
// Variable: navigationQuery
// Query: *[_type == "navigation"][0]{    "items": items[]{_key, label, command, route}  }
export type NavigationQueryResult = {
  items: Array<{
    _key: string
    label: string
    command: string
    route: Array<string> | null
  }> | null
} | null

// Source: sanity/lib/queries.ts
// Variable: homePageQuery
// Query: *[_type == "homePage"][0]{    _id,    heroHeading,    heroSub,    heroBio,    "metrics": metrics[]{_key, number, unit, label},    "nextSteps": nextSteps[]{_key, cmd, flag, description},    "featuredProjects": featuredProjects[]->{_id, title, "slug": slug.current, commit, status, tags},    "systemCard": systemCard{      "kvRows": kvRows[]{_key, key, value}    }  }
export type HomePageQueryResult = {
  _id: string
  heroHeading: null
  heroSub: null
  heroBio: null
  metrics: Array<{
    _key: string
    number: null
    unit: string | null
    label: string | null
  }> | null
  nextSteps: Array<{
    _key: string
    cmd: string
    flag: string | null
    description: null
  }> | null
  featuredProjects: Array<{
    _id: string
    title: string
    slug: string
    commit: string
    status: 'active' | 'archived' | 'live' | 'shipped'
    tags: Array<
      {
        _key: string
      } & TagReference
    >
  }> | null
  systemCard: {
    kvRows: Array<{
      _key: string
      key: string | null
      value: string | null
    }> | null
  } | null
} | null

// Source: sanity/lib/queries.ts
// Variable: aboutPageQuery
// Query: *[_type == "aboutPage"][0]{    _id,    "bioParagraphs": bioParagraphs[],    "timeline": timeline[]{_key, year, title, company, description, lit},    "values": values[]{_key, title, description},    "stackRows": stackRows[]{_key, category, tools[]},    "ctas": ctas[]{_key, label, href, primary}  }
export type AboutPageQueryResult = {
  _id: string
  bioParagraphs: Array<string> | null
  timeline: Array<{
    _key: string
    year: null
    title: null
    company: string | null
    description: null
    lit: null
  }> | null
  values: Array<{
    _key: string
    title: null
    description: null
  }> | null
  stackRows: Array<{
    _key: string
    category: null
    tools: null
  }> | null
  ctas: Array<{
    _key: string
    label: null
    href: null
    primary: boolean | null
  }> | null
} | null

// Source: sanity/lib/queries.ts
// Variable: portfolioPageQuery
// Query: *[_type == "portfolioPage"][0]{    _id,    eyebrow,    heading,    intro,    filterLabel,    "detailLabels": detailLabels{      role,      problem,      solution,      stack,      impact    }  }
export type PortfolioPageQueryResult = {
  _id: string
  eyebrow: string | null
  heading: string | null
  intro: string | null
  filterLabel: string | null
  detailLabels: {
    role: null
    problem: null
    solution: null
    stack: null
    impact: null
  } | null
} | null

// Source: sanity/lib/queries.ts
// Variable: blogPageQuery
// Query: *[_type == "blogPage"][0]{    _id,    heading,    intro,    "articleLabels": articleLabels{      recentHeading,      featuredLabel,      readMore,      minRead    }  }
export type BlogPageQueryResult = {
  _id: string
  heading: string | null
  intro: string | null
  articleLabels: {
    recentHeading: string | null
    featuredLabel: null
    readMore: null
    minRead: null
  } | null
} | null

// Source: sanity/lib/queries.ts
// Variable: contactPageQuery
// Query: *[_type == "contactPage"][0]{    _id,    heading,    intro,    "formFields": formFields{      namePlaceholder,      emailPlaceholder,      messagePlaceholder,      submitLabel    },    "validationMessages": validationMessages{      nameRequired,      emailInvalid,      messageRequired    },    "successLines": successLines[]  }
export type ContactPageQueryResult = {
  _id: string
  heading: string | null
  intro: string | null
  formFields: null
  validationMessages: {
    nameRequired: string | null
    emailInvalid: string | null
    messageRequired: string | null
  } | null
  successLines: Array<string> | null
} | null

// Source: sanity/lib/queries.ts
// Variable: projectQuery
// Query: *[_type == "project" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    commit,    status,    tags,    role,    "problem": problem[],    "solution": solution[],    "stack": stack[],    "impact": impact[],    "coverImage": coverImage{asset, alt, crop, hotspot},    "gallery": gallery[]{_key, "image": image{asset, alt, crop, hotspot}},    repo,    live,    order,    "seo": seo{title, description, ogImage}  }
export type ProjectQueryResult = {
  _id: string
  title: string
  slug: string
  commit: string
  status: 'active' | 'archived' | 'live' | 'shipped'
  tags: Array<
    {
      _key: string
    } & TagReference
  >
  role: string | null
  problem: null
  solution: null
  stack: Array<string> | null
  impact: Array<string> | null
  coverImage: {
    asset: SanityImageAssetReference | null
    alt: string | null
    crop: SanityImageCrop | null
    hotspot: SanityImageHotspot | null
  }
  gallery: Array<{
    _key: string
    image: null
  }> | null
  repo: string | null
  live: string | null
  order: number | null
  seo: {
    title: null
    description: null
    ogImage: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      metadataBase?: string
      _type: 'image'
    } | null
  } | null
} | null

// Source: sanity/lib/queries.ts
// Variable: allProjectsQuery
// Query: *[_type == "project"] | order(order asc, _createdAt desc){    _id,    title,    "slug": slug.current,    commit,    status,    tags,    role,    "problem": problem[],    "coverImage": coverImage{asset, alt, crop, hotspot},    repo,    live,    order  }
export type AllProjectsQueryResult = Array<{
  _id: string
  title: string
  slug: string
  commit: string
  status: 'active' | 'archived' | 'live' | 'shipped'
  tags: Array<
    {
      _key: string
    } & TagReference
  >
  role: string | null
  problem: null
  coverImage: {
    asset: SanityImageAssetReference | null
    alt: string | null
    crop: SanityImageCrop | null
    hotspot: SanityImageHotspot | null
  }
  repo: string | null
  live: string | null
  order: number | null
}>

// Source: sanity/lib/queries.ts
// Variable: portfolioPostQuery
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    summary,    "date": coalesce(date, _updatedAt),    category,    "tags": tags[]{_key, ...@->{_id, title, "slug": slug.current}},    readTime,    featured,    "coverImage": coverImage{asset, alt, crop, hotspot},    body,    "seo": seo{title, description, ogImage}  }
export type PortfolioPostQueryResult = {
  _id: string
  title: string
  slug: string
  summary: string
  date: string
  category: CategoryReference
  tags: Array<{
    _key: string
    _id: string
    title: string
    slug: string
  }> | null
  readTime: number | null
  featured: boolean | null
  coverImage: {
    asset: SanityImageAssetReference | null
    alt: string | null
    crop: SanityImageCrop | null
    hotspot: SanityImageHotspot | null
  }
  body: BlockContent | null
  seo: {
    title: null
    description: null
    ogImage: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      metadataBase?: string
      _type: 'image'
    } | null
  } | null
} | null

// Source: sanity/lib/queries.ts
// Variable: qaEntryQuery
// Query: *[_type == "qaEntry" && enabled != false] | order(_createdAt asc){    _id,    title,    "keywords": keywords[],    "answer": answer[],    "action": action{cmd, flag, route},    enabled  }
export type QaEntryQueryResult = Array<{
  _id: string
  title: string
  keywords: Array<string>
  answer: Array<string> | null
  action: {
    cmd: string | null
    flag: string | null
    route: Array<string> | null
  } | null
  enabled: boolean | null
}>

// Source: sanity/lib/queries.ts
// Variable: BLOG_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc){    _id,    _type,    title,    "slug": slug.current,    summary,    "date": coalesce(date, _updatedAt),    "category": category->{_id, title, "slug": slug.current},    "tags": tags[]{_key, ...@->{_id, title, "slug": slug.current}},    readTime,    featured,    "coverImage": coverImage{asset, alt, crop, hotspot}  }
export type BLOG_POSTS_QUERY_RESULT = Array<{
  _id: string
  _type: 'post'
  title: string
  slug: string
  summary: string
  date: string
  category: {
    _id: string
    title: string
    slug: string
  }
  tags: Array<{
    _key: string
    _id: string
    title: string
    slug: string
  }> | null
  readTime: number | null
  featured: boolean | null
  coverImage: {
    asset: SanityImageAssetReference | null
    alt: string | null
    crop: SanityImageCrop | null
    hotspot: SanityImageHotspot | null
  }
}>

// Source: sanity/lib/queries.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc){    _id,    title,    "slug": slug.current  }
export type ALL_CATEGORIES_QUERY_RESULT = Array<{
  _id: string
  title: string
  slug: string
}>

// Source: sanity/lib/queries.ts
// Variable: RECENT_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc)[0...5]{    _id,    title,    "slug": slug.current,    "date": coalesce(date, _updatedAt),    summary,    readTime  }
export type RECENT_POSTS_QUERY_RESULT = Array<{
  _id: string
  title: string
  slug: string
  date: string
  summary: string
  readTime: number | null
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "settings"][0]': SettingsQueryResult
    '\n  *[_type == "siteSettings"][0]{\n    name,\n    headline,\n    shortBio,\n    github,\n    linkedin,\n    seo {\n      metaTitle,\n      metaDescription,\n      ogImage\n    }\n  }\n': SETTINGS_QUERY_RESULT
    '\n  *[_id == "homePage"][0]{\n    seo {\n      metaTitle,\n      metaDescription,\n      ogImage\n    }\n  }\n': HOME_PAGE_META_QUERY_RESULT
    '\n  *[_id == "aboutPage"][0]{\n    seo {\n      metaTitle,\n      metaDescription,\n      ogImage\n    }\n  }\n': ABOUT_PAGE_META_QUERY_RESULT
    '\n  *[_id == "portfolioPage"][0]{\n    heading,\n    intro,\n    seo {\n      metaTitle,\n      metaDescription,\n      ogImage\n    }\n  }\n': PORTFOLIO_PAGE_META_QUERY_RESULT
    '\n  *[_id == "blogPage"][0]{\n    heading,\n    intro,\n    seo {\n      metaTitle,\n      metaDescription,\n      ogImage\n    }\n  }\n': BLOG_PAGE_META_QUERY_RESULT
    '\n  *[_id == "contactPage"][0]{\n    heading,\n    seo {\n      metaTitle,\n      metaDescription,\n      ogImage\n    }\n  }\n': CONTACT_PAGE_META_QUERY_RESULT
    '\n  *[_type == "project" && slug.current == $slug][0]{\n    title,\n    "slug": slug.current,\n    _updatedAt,\n    coverImage,\n    seo {\n      metaTitle,\n      metaDescription,\n      ogImage\n    }\n  }\n': PROJECT_META_QUERY_RESULT
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    title,\n    summary,\n    "slug": slug.current,\n    date,\n    _updatedAt,\n    coverImage,\n    seo {\n      metaTitle,\n      metaDescription,\n      ogImage\n    }\n  }\n': POST_META_QUERY_RESULT
    '\n  *[_type == "project" && defined(slug.current)]{\n    "slug": slug.current,\n    _updatedAt\n  }\n': PROJECTS_SLUG_QUERY_RESULT
    '\n  *[_type == "post" && defined(slug.current)]{\n    "slug": slug.current,\n    date,\n    _updatedAt\n  }\n': POSTS_SLUG_QUERY_RESULT
    '\n  *[_type == "post" && defined(slug.current)] | order(date desc) [0...20] {\n    title,\n    "slug": slug.current,\n    summary,\n    date,\n    "categoryTitle": category->title\n  }\n': RSS_POSTS_QUERY_RESULT
    '\n  *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {\n    _id,\n    "status": select(_originalId in path("drafts.**") => "draft", "published"),\n    "title": coalesce(title, "Untitled"),\n    "slug": slug.current,\n    excerpt,\n    coverImage,\n    "date": coalesce(date, _updatedAt),\n    "author": author->{firstName, lastName, picture},\n  }\n': AllPostsQueryResult
    '\n  *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {\n    _id,\n    "status": select(_originalId in path("drafts.**") => "draft", "published"),\n    "title": coalesce(title, "Untitled"),\n    "slug": slug.current,\n    excerpt,\n    coverImage,\n    "date": coalesce(date, _updatedAt),\n    "author": author->{firstName, lastName, picture},\n  }\n': MorePostsQueryResult
    '\n  *[_type == "post" && slug.current == $slug] [0] {\n    content[]{\n      ...,\n      markDefs[]{\n        ...,\n        _type == "link" => {\n          "page": page->slug.current,\n          "post": post->slug.current\n        }\n      }\n    },\n    _id,\n    "status": select(_originalId in path("drafts.**") => "draft", "published"),\n    "title": coalesce(title, "Untitled"),\n    "slug": slug.current,\n    excerpt,\n    coverImage,\n    "date": coalesce(date, _updatedAt),\n    "author": author->{firstName, lastName, picture},\n  }\n': PostQueryResult
    '\n  *[_type == "post" && defined(slug.current)]\n  {"slug": slug.current}\n': PostPagesSlugsResult
    '\n  *[_type == "page" && defined(slug.current)]\n  {"slug": slug.current}\n': PagesSlugsResult
    '\n  *[_type == \'page\' && slug.current == $slug][0]{\n    _id,\n    _type,\n    name,\n    slug,\n    heading,\n    subheading,\n    "pageBuilder": pageBuilder[]{\n      ...,\n      _type == "callToAction" => {\n        ...,\n        button {\n          ...,\n          link {\n            ...,\n            _type == "link" => {\n              "page": page->slug.current,\n              "post": post->slug.current\n            }\n          }\n        }\n      },\n      _type == "infoSection" => {\n        content[]{\n          ...,\n          markDefs[]{\n            ...,\n            _type == "link" => {\n              "page": page->slug.current,\n              "post": post->slug.current\n            }\n          }\n        }\n      },\n    },\n  }\n': GetPageQueryResult
    '\n  *[_type == "page" || _type == "post" && defined(slug.current)] | order(_type asc) {\n    "slug": slug.current,\n    _type,\n    _updatedAt,\n  }\n': SitemapDataResult
    '\n  *[_type == "siteSettings"][0]{\n    _id,\n    siteTitle,\n    tagline,\n    bio,\n    email,\n    github,\n    linkedin,\n    twitter,\n    "portrait": portrait{asset, alt, crop, hotspot},\n    "seo": seo{title, description, ogImage},\n    "theme": theme{accentColor, grain, heroLayout},\n    "homePage": homePage{\n      heroHeading,\n      heroSub,\n      heroBio,\n      "metrics": metrics[]{_key, number, unit, label},\n      "nextSteps": nextSteps[]{_key, cmd, flag, description},\n      "featuredProjects": featuredProjects[]->{_id, title, "slug": slug.current, commit, status, tags},\n      "systemCard": systemCard{\n        "kvRows": kvRows[]{_key, key, value}\n      }\n    }\n  }\n': SiteSettingsQueryResult
    '\n  *[_type == "navigation"][0]{\n    "items": items[]{_key, label, command, route}\n  }\n': NavigationQueryResult
    '\n  *[_type == "homePage"][0]{\n    _id,\n    heroHeading,\n    heroSub,\n    heroBio,\n    "metrics": metrics[]{_key, number, unit, label},\n    "nextSteps": nextSteps[]{_key, cmd, flag, description},\n    "featuredProjects": featuredProjects[]->{_id, title, "slug": slug.current, commit, status, tags},\n    "systemCard": systemCard{\n      "kvRows": kvRows[]{_key, key, value}\n    }\n  }\n': HomePageQueryResult
    '\n  *[_type == "aboutPage"][0]{\n    _id,\n    "bioParagraphs": bioParagraphs[],\n    "timeline": timeline[]{_key, year, title, company, description, lit},\n    "values": values[]{_key, title, description},\n    "stackRows": stackRows[]{_key, category, tools[]},\n    "ctas": ctas[]{_key, label, href, primary}\n  }\n': AboutPageQueryResult
    '\n  *[_type == "portfolioPage"][0]{\n    _id,\n    eyebrow,\n    heading,\n    intro,\n    filterLabel,\n    "detailLabels": detailLabels{\n      role,\n      problem,\n      solution,\n      stack,\n      impact\n    }\n  }\n': PortfolioPageQueryResult
    '\n  *[_type == "blogPage"][0]{\n    _id,\n    heading,\n    intro,\n    "articleLabels": articleLabels{\n      recentHeading,\n      featuredLabel,\n      readMore,\n      minRead\n    }\n  }\n': BlogPageQueryResult
    '\n  *[_type == "contactPage"][0]{\n    _id,\n    heading,\n    intro,\n    "formFields": formFields{\n      namePlaceholder,\n      emailPlaceholder,\n      messagePlaceholder,\n      submitLabel\n    },\n    "validationMessages": validationMessages{\n      nameRequired,\n      emailInvalid,\n      messageRequired\n    },\n    "successLines": successLines[]\n  }\n': ContactPageQueryResult
    '\n  *[_type == "project" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    commit,\n    status,\n    tags,\n    role,\n    "problem": problem[],\n    "solution": solution[],\n    "stack": stack[],\n    "impact": impact[],\n    "coverImage": coverImage{asset, alt, crop, hotspot},\n    "gallery": gallery[]{_key, "image": image{asset, alt, crop, hotspot}},\n    repo,\n    live,\n    order,\n    "seo": seo{title, description, ogImage}\n  }\n': ProjectQueryResult
    '\n  *[_type == "project"] | order(order asc, _createdAt desc){\n    _id,\n    title,\n    "slug": slug.current,\n    commit,\n    status,\n    tags,\n    role,\n    "problem": problem[],\n    "coverImage": coverImage{asset, alt, crop, hotspot},\n    repo,\n    live,\n    order\n  }\n': AllProjectsQueryResult
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    "date": coalesce(date, _updatedAt),\n    category,\n    "tags": tags[]{_key, ...@->{_id, title, "slug": slug.current}},\n    readTime,\n    featured,\n    "coverImage": coverImage{asset, alt, crop, hotspot},\n    body,\n    "seo": seo{title, description, ogImage}\n  }\n': PortfolioPostQueryResult
    '\n  *[_type == "qaEntry" && enabled != false] | order(_createdAt asc){\n    _id,\n    title,\n    "keywords": keywords[],\n    "answer": answer[],\n    "action": action{cmd, flag, route},\n    enabled\n  }\n': QaEntryQueryResult
    '\n  *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc){\n    _id,\n    _type,\n    title,\n    "slug": slug.current,\n    summary,\n    "date": coalesce(date, _updatedAt),\n    "category": category->{_id, title, "slug": slug.current},\n    "tags": tags[]{_key, ...@->{_id, title, "slug": slug.current}},\n    readTime,\n    featured,\n    "coverImage": coverImage{asset, alt, crop, hotspot}\n  }\n': BLOG_POSTS_QUERY_RESULT
    '\n  *[_type == "category"] | order(title asc){\n    _id,\n    title,\n    "slug": slug.current\n  }\n': ALL_CATEGORIES_QUERY_RESULT
    '\n  *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc)[0...5]{\n    _id,\n    title,\n    "slug": slug.current,\n    "date": coalesce(date, _updatedAt),\n    summary,\n    readTime\n  }\n': RECENT_POSTS_QUERY_RESULT
  }
}
