/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../sanity.schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h2' | 'h3' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'external' | 'internal'
        href?: string
        route?: string
        newTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | ({
      _key: string
    } & Code)
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      caption?: string
      _type: 'image'
      _key: string
    }
>

export type Seo = {
  _type: 'seo'
  metaTitle?: string
  metaDescription?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
}

export type QaAction = {
  _type: 'qaAction'
  cmd?: string
  flag?: string
  route?: Array<string>
}

export type CtaCommand = {
  _type: 'ctaCommand'
  cmd: string
  flag?: string
  sub?: string
  primary?: boolean
  route?: Array<string>
}

export type StackRow = {
  _type: 'stackRow'
  term?: string
  items?: Array<string>
}

export type ValueItem = {
  _type: 'valueItem'
  key?: string
  value?: string
}

export type TimelineEntry = {
  _type: 'timelineEntry'
  years?: string
  role?: string
  company?: string
  body?: string
  current?: boolean
}

export type Metric = {
  _type: 'metric'
  value?: string
  unit?: string
  label?: string
}

export type QaEntry = {
  _id: string
  _type: 'qaEntry'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  keywords: Array<string>
  answer?: Array<string>
  action?: QaAction
  enabled?: boolean
}

export type Tag = {
  _id: string
  _type: 'tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type CategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'category'
}

export type TagReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'tag'
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  summary: string
  date: string
  category: CategoryReference
  tags?: Array<
    {
      _key: string
    } & TagReference
  >
  readTime?: number
  featured?: boolean
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    imagePrompt?: string
    _type: 'image'
  }
  body?: BlockContent
  seo?: Seo
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Category = {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  description?: string
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  commit: string
  status: 'live' | 'shipped' | 'active' | 'archived'
  tags: Array<
    {
      _key: string
    } & TagReference
  >
  role?: string
  problem: string
  solution: string
  stack?: Array<string>
  impact?: Array<string>
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    imagePrompt?: string
    _type: 'image'
  }
  gallery?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'image'
    _key: string
  }>
  repo?: string
  live?: string
  order?: number
  seo?: Seo
}

export type ContactPage = {
  _id: string
  _type: 'contactPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  eyebrow?: string
  heading?: string
  intro?: string
  formTitle?: string
  formBadge?: string
  nameField?: {
    label?: string
    placeholder?: string
  }
  emailField?: {
    label?: string
    placeholder?: string
  }
  messageField?: {
    label?: string
    placeholder?: string
  }
  submitLabel?: string
  formNote?: string
  validationMessages?: {
    nameRequired?: string
    emailRequired?: string
    emailInvalid?: string
    messageRequired?: string
    messageTooShort?: string
  }
  successPanelTitle?: string
  successLines?: Array<string>
  successGreeting?: string
  sendAnotherLabel?: string
  availabilityHeading?: string
  availabilityText?: string
  resumeLabel?: string
  seo?: Seo
}

export type BlogPage = {
  _id: string
  _type: 'blogPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  eyebrow?: string
  heading?: string
  intro?: string
  featuredPanelTitle?: string
  featuredBadge?: string
  readButtonLabel?: string
  searchPlaceholder?: string
  noMatchesText?: string
  loadingText?: string
  endText?: string
  archiveLabel?: string
  archiveNote?: string
  articleLabels?: {
    tocHeading?: string
    searchHeading?: string
    categoriesHeading?: string
    tagsHeading?: string
    recentHeading?: string
    archivesHeading?: string
    readingTimeHeading?: string
    categoryHeading?: string
    moreNotesHeading?: string
    backLabel?: string
    figCaptionPrefix?: string
  }
  seo?: Seo
}

export type PortfolioPage = {
  _id: string
  _type: 'portfolioPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  eyebrow?: string
  heading?: string
  intro?: string
  filterLabel?: string
  matchesText?: string
  loadingText?: string
  endText?: string
  detailLabels?: {
    deployLogTitle?: string
    deployLogLines?: Array<string>
    briefHeading?: string
    problemLabel?: string
    solutionLabel?: string
    stackLabel?: string
    roleLabel?: string
    impactHeading?: string
    interfaceHeading?: string
    cloneLabel?: string
    openLiveLabel?: string
    backLabel?: string
    prevLabel?: string
    nextLabel?: string
  }
  seo?: Seo
}

export type AboutPage = {
  _id: string
  _type: 'aboutPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  eyebrow?: string
  heading?: string
  portraitCaption?: string
  bioParagraphs?: Array<string>
  experiencePrompt?: string
  timeline?: Array<
    {
      _key: string
    } & TimelineEntry
  >
  valuesPrompt?: string
  values?: Array<
    {
      _key: string
    } & ValueItem
  >
  stackPrompt?: string
  stackRows?: Array<
    {
      _key: string
    } & StackRow
  >
  ctas?: Array<
    {
      _key: string
    } & CtaCommand
  >
  seo?: Seo
}

export type ProjectReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'project'
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  heroWord: string
  promptCommand?: string
  toolActions?: Array<string>
  successLines?: Array<string>
  portraitCaption?: string
  featuredHeading?: string
  featuredProjects?: Array<
    {
      _key: string
    } & ProjectReference
  >
  metricsHeading?: string
  metrics?: Array<
    {
      _key: string
    } & Metric
  >
  nextStepsHeading?: string
  nextSteps?: Array<
    {
      _key: string
    } & CtaCommand
  >
  systemCard?: {
    roleLine?: string
    kvRows?: Array<
      {
        _key: string
      } & ValueItem
    >
  }
  seo?: Seo
}

export type Navigation = {
  _id: string
  _type: 'navigation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  items?: Array<{
    label: string
    command: string
    route?: Array<string>
    _type: 'item'
    _key: string
  }>
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  handle: string
  headline: string
  shortBio: string
  email: string
  location?: string
  availability?: string
  availabilityStatus?: boolean
  cv?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
  portrait?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  github?: string
  linkedin?: string
  theme?: {
    accentColor?: Color
    grain?: boolean
    heroLayout?: 'boot' | 'split'
  }
  askConsole?: {
    enabled?: boolean
    heading?: string
    description?: string
    placeholder?: string
    emptyMessage?: string
    suggestions?: Array<string>
    fallback?: Array<string>
  }
  statusbar?: {
    branchLabel?: string
    statusText?: string
  }
  uiText?: {
    notFoundTitle?: string
    notFoundBody?: string
    commandPalettePlaceholder?: string
    mobileConsolePrompt?: string
    newSessionLabel?: string
    copyEmailLabel?: string
  }
  seo?: Seo
}

export type Color = {
  _type: 'color'
  hex?: string
  alpha?: number
  hsl?: HslaColor
  hsv?: HsvaColor
  rgb?: RgbaColor
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type Code = {
  _type: 'code'
  language?: string
  filename?: string
  code?: string
  highlightedLines?: Array<number>
}

export type RgbaColor = {
  _type: 'rgbaColor'
  r?: number
  g?: number
  b?: number
  a?: number
}

export type HsvaColor = {
  _type: 'hsvaColor'
  h?: number
  s?: number
  v?: number
  a?: number
}

export type HslaColor = {
  _type: 'hslaColor'
  h?: number
  s?: number
  l?: number
  a?: number
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | BlockContent
  | Seo
  | QaAction
  | CtaCommand
  | StackRow
  | ValueItem
  | TimelineEntry
  | Metric
  | QaEntry
  | Tag
  | Slug
  | CategoryReference
  | TagReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Category
  | Project
  | ContactPage
  | BlogPage
  | PortfolioPage
  | AboutPage
  | ProjectReference
  | HomePage
  | Navigation
  | SanityFileAssetReference
  | SiteSettings
  | Color
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | Code
  | RgbaColor
  | HsvaColor
  | HslaColor
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
